export const PAGE_BUTTON_CLICK = "PAGE_BUTTON_CLICK";
export const PAGE_MOVE_INDEX = "PAGE_MOVE_INDEX";

export const SCROLL_MOVING_TRUE = "SCROLL_MOVING_TRUE";
export const ABOUT_PAGE_SCROLL_TRUE = "ABOUT_PAGE_SCROLL_TRUE";
